services:
  develop:
    build: .
    ports:
      - "3000:3000"
    container_name: fw-users # TODO: Update name in final service
    environment:
      PORT: 3000
    volumes:
      - ./app:/opt/fw-users/app # TODO: Update fw-users in final service
      - ./config:/opt/fw-users/config # TODO: Update fw-users in final service
      - ./nodemon.json:/opt/fw-users/nodemon.json # TODO: fw-users name in final service
    command: yarn dev

  test:
    build: .
    container_name: fw-users-test # TODO: Update name in final service
    volumes:
      - ./app:/opt/fw-users/app # TODO: Update fw-users in final service
      - ./config:/opt/fw-users/config # TODO: Update fw-users in final service
      - ./nodemon.json:/opt/fw-users/nodemon.json # TODO: Update fw-users in final service
      - ./jest.config.js:/opt/fw-users/jest.config.js # TODO: Update fw-users in final service
    command: yarn test

  docs:
    build: .
    ports:
      - "30000:30000"
    container_name: fw-users-docs # TODO: Update name in final service
    volumes:
      - ./docs:/opt/fw-users/docs # TODO: Update fw-users in final service
    command: yarn run docs -l 30000