services:
  develop:
    build: .
    ports:
      - "3001:3001"
    container_name: fw-users
    environment:
      PORT: 3001
      LOGGER_LEVEL: debug
      AUTH_URL: https://staging-api.resourcewatch.org
      FORMS_API_URL: https://dev-fw-api.globalforestwatch.org/v3/gfw/templates
      AREAS_API_URL: https://dev-fw-api.globalforestwatch.org/v3/gfw/areas
      LAYERS_API_URL: https://dev-fw-api.globalforestwatch.org/v3/contextual-layer
      TEAMS_API_URL: https://dev-fw-api.globalforestwatch.org/v3/gfw/teams
      SPARKPOST_API_KEY: ${sparkpost_api_key}
    volumes:
      - ./app:/opt/fw-users/app
      - ./config:/opt/fw-users/config
      - ./nodemon.json:/opt/fw-users/nodemon.json
    command: yarn dev

  test:
    build: .
    container_name: fw-users-test
    environment:
      PORT: 0
      NODE_ENV: test
      LOGGER_LEVEL: debug
      SUPPRESS_NO_CONFIG_WARNING: "true"
      AUTH_URL: http://127.0.0.1:9000
      FORMS_API_URL: http://127.0.0.1:9000
      AREAS_API_URL: http://127.0.0.1:9000
      LAYERS_API_URL: http://127.0.0.1:9000
      TEAMS_API_URL: http://127.0.0.1:9000
      API_VERSION: v1
    volumes:
      - ./app:/opt/fw-users/app
      - ./config:/opt/fw-users/config
      - ./nodemon.json:/opt/fw-users/nodemon.json
      - ./jest.config.js:/opt/fw-users/jest.config.js
    command: yarn test

  docs:
    build: .
    ports:
      - "30010:30010"
    container_name: fw-users-docs
    volumes:
      - ./docs:/opt/fw-users/docs
    command: yarn run docs -l 30010