openapi: 3.1.0
info:
  title: fw_users
  version: '1.0'
  summary: Users Microservice
  description: Microservice to handle user specific requests
servers:
  - description: Dev
    url: 'https://dev-fw-api.globalforestwatch.org/v1/users'
  - url: 'https://staging-fw-api.globalforestwatch.org/v1/users'
    description: Staging
  - url: 'https://api.resourcewatch.org/v1/users'
    description: Production
  - url: 'http://localhost:3001/v1/users'
    description: Local
paths:
  /users:
    delete:
      summary: Delete Current User
      operationId: delete-v1-users
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
      description: Deletes all data held by 3 sided cube for the existing user. Will return a 400 error if user is admin of a team and a 401 error if user is not authorised
    parameters: []
components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
  responses:
    Error:
      description: Error Response
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              errors:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  required:
                    - status
                    - detail
                  properties:
                    status:
                      type: number
                    detail:
                      type: string
                      minLength: 1
            required:
              - errors
          examples: {}
    Healthcheck:
      description: Healthcheck response
      content:
        application/json:
          schema:
            type: object
            properties:
              uptime:
                type: number
          examples: {}
security:
  - Authorization: []
