openapi: 3.1.0
info:
  title: fw_service_template # TODO: Update name in final service
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: Local
paths:
components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
  responses:
    Error:
      description: Error Response
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              errors:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  required:
                    - status
                    - detail
                  properties:
                    status:
                      type: number
                    detail:
                      type: string
                      minLength: 1
            required:
              - errors
          examples: {}
    Healthcheck:
      description: Healthcheck response
      content:
        application/json:
          schema:
            type: object
            properties:
              uptime:
                type: number
          examples: {}
security:
  - Authorization: []
